---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
     - echo "Installing flyway..."
      - sh -c 'echo "docker run --rm flyway/flyway:6.0.4 $*" > /usr/local/bin/flyway && chmod +x /usr/local/bin/flyway'
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - python MigrateDatabase.py
